### ISSUE TITLE
Amber does not build with clang 5.0.

### ISSUE THREAD

**Issue by s-perron** [google/amber#278]
I tried compiling amber with clang-5.0, and I get this error:

```
../samples/config_helper_vulkan.cc:736:27: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
  if (vulkan_instance_ != VK_NULL_HANDLE)
                          ^~~~~~~~~~~~~~
                          nullptr
/usr/include/vulkan/vulkan.h:49:24: note: expanded from macro 'VK_NULL_HANDLE'
#define VK_NULL_HANDLE 0
```
